### ISSUE TITLE
Chunks

### ISSUE THREAD

**Issue by dmartin015** [PowerNukkit/Plugin-AntiXray#3]
Chunks don't load me in any way

![image](https://user-images.githubusercontent.com/69425536/124935943-6989db80-e006-11eb-9ef1-6cbe66781973.png)

**Comment by MonoAdrian23** [comment]
Check youre Internet connection. 
I use the same Plugin but without Problems.

**Comment by dmartin015** [comment]
My Internet connection its okay

**Comment by Gabriel8579** [comment]
Please attach config.yml and send us the `/debug upload` command result

**Comment by MonoAdrian23** [comment]
But when you try to use Xray

[36m16:41:07[m [[m[1;31mERROR[m[m] An exception occurred in RakNet (Server)

io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Operation not permitted


This crashs my server

This issue happens everytime with to many packages.

**Comment by Gabriel8579** [comment]
> But when you try to use Xray
> 
> [36m16:41:07[m [[m[1;31mERROR[m[m] An exception occurred in RakNet (Server)
> 
> io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Operation not permitted
> 
> This crashs my server
> 
> This issue happens everytime with to many packages.

The same problem was reported in PowerNukkit even without using this plugin, could you test if it keeps happening when removing the plugin? If so, please open another issue

**Comment by MonoAdrian23** [comment]
Yes this error happens without this plugin too. 
This Operation not Permitted sucks a little bit because i must restart my Server everytime. 
And i cant hold my server as long this bug exist. 

I have deinstall all, Scorboard, Mtu set to 700 and nothing works. 
This is a High Priority Issue. 

But this error happens more with AntiXray 
Over 30000 Times in my Console. 
100% Ram Usage
Normal 50%

A player cant interact ingame anymore. 

Raknet Devs:

- Bad Packages
- Worlds (Modified) 
- Inventory or Spawn Plugins (EasySpawns) or Fakeinventories) 
- All Join Events

**Comment by Gabriel8579** [comment]
In this case with the plugin we don't have much to do, as it needs to send the packets of all loadable chunks to the player to all players on the server and monitor all block updates to remove the x-ray protection when the players is legitimately mining or something, we will continue to discuss this issue at https://github.com/PowerNukkit/PowerNukkit/issues/1056

**Comment by Gabriel8579** [comment]
Maybe in the next minor release this should improve a little as I'm making some modifications to the way the packet is sent but it shouldn't solve the problem since the problem is in the raknet layer

**Comment by MonoAdrian23** [comment]
I can confirm this issue now. 
I can find more diamonds with this plugin

**Comment by dmartin015** [comment]
Hello my debug paste https://debugpaste.powernukkit.org/pastes/PNc4e552ff/
And my config.yml https://pastebin.com/GHPLt7AQ
I have the last powernukkit version too

**Comment by Gabriel8579** [comment]
Can you try setting asyc-compression to true in nukkit.yml?

**Comment by TheDiego845** [comment]
> Can you try setting asyc-compression to true in nukkit.yml?

00:41:19 [INFO ] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
00:41:19 [ERROR] Catching
java.lang.NullPointerException: null
        at cn.nukkit.permission.BanList.load(BanList.java:111) ~[server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:605) ~[server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:199) [server.jar:?]

**Comment by dmartin015** [comment]
I think I found the problem I tried in another world that barely weighs 200mb and if it works later I tried in my survival world that weighs approximately 4gb and does not work I do not know if there is a solution

**Comment by dmartin015** [comment]
Close this if nobody knows the problem
